services:
  website:
    image:
      website
    environment:
      DB_URL: "${DB_URL}"
      HTTP_ONLY: "${HTTP_ONLY}"
      EMAIL: "${EMAIL}"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db

  db:
    image: 
      db
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
